url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Freunde des Lighthouse
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Dr. Florian Neuhann
  pic: 1
  position: 1. Vorsitzender

- name: Dr. Ulrike Steinhoff
  pic: 2
  position: 2. Vorsitzende

- name: Prof. Dr. Gerd Fätkenheuer
  pic: 3
  position: Schatzmeister
  social:

- name: Prof. Dr. Paul Schnitzler
  pic: 4
  position: Schriftführer
  social:

- name: Julia Tabatabai
  pic: 5
  position: Inhaltgestaltung
  social:

- name: Florian Scheibe
  pic: 6
  position: Inhaltgestaltung
  social:


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
